### ISSUE TITLE
Nested Arrays of Objects

### ISSUE THREAD

**Issue by eliezercazarestravelport** [birddevelper/jQueryJsonToTable#1]
Hello Bird,

Thanks for your plugin! it's helping to some extent.
However, nested arrays of objects (meaning it can be in the first level, second level and even a third level at once) are not rendered. It renders [object Object]

I believe this is causing it?

    // if data is given as json array, no proccess needed
    if(checkType(options.data)=="Array"){
        jsonData = options.data;
    }

**Comment by birddevelper** [comment]
Hi Eliezer, 

This plugin only works with the objects nested in the first level of the main object. Currently it doesn't support nested array of objects.

I think this JS library can meet your requirements : 

[https://www.npmjs.com/package/nested-json-to-table?activeTab=explore](https://www.npmjs.com/package/nested-json-to-table?activeTab=explore)  

The only problem with this library is that you need to translate the documentation and sample codes.

**Comment by eliezercazarestravelport** [comment]
> Hi Eliezer,
> 
> This plugin only works with the objects nested in the first level of the main object. Currently it doesn't support nested array of objects.
> 
> I think this JS library can meet your requirements :
> 
> https://www.npmjs.com/package/nested-json-to-table?activeTab=explore
> 
> The only problem with this library is that you need to translate the documentation and sample codes.

Thank you so much! 
I will take a look at that one.
Yours works fine as designed. 
Thanks for sharing!
